### ISSUE TITLE
Add dat mirror for the released dataset

### ISSUE THREAD

**Issue by millette** [librariesio/libraries.io#1506] opened 2017-06-15 19:03 UTC
<del>Add ```dat://49bd045de3beb9abcb7272967e2fb16e07b96c06e15cd814f703e8581d4561e5``` to <https://libraries.io/data> as a mirror.</del>

Note that instead of a zip, the dat holds each file and the csv files were gzipped to save space. <del>The content is available: <https://datproject.org/view?query=49bd045de3beb9abcb7272967e2fb16e07b96c06e15cd814f703e8581d4561e5></del>

Since there's no more zip, it's probably a good idea to provide md5 for all file (both gzipped and not).

**EDIT**: Updated https://datproject.org link above.

**EDIT#2**: Dat removed on my end.

**Comment by joehand** [comment] 2017-06-15 21:01
Nice! Let us know when this is published as a mirror and we can host it on another peer.

Previewing massive csv files is in our TODOs for datproject.org. This would be a cool dataset to demo =).

> Since there's no more zip, it's probably a good idea to provide md5 for all file (both gzipped and not).

Dat will verify the content integrity when downloading, so this won't be strictly necessary for users downloading via dat. But may still be good if you want to download via http.

**Comment by millette** [comment] 2017-06-15 21:13
In this case, I'm not the original publisher, I could mess with the content of the dat (not that I will). Having the right md5 at libraries.io lets users know they got the right stuff.

**Comment by rmg** [comment] 2017-07-09 00:11
Went to download the dataset and when I saw it was 5.5G I nearly opened a duplicate of this issue before finding this one. It seems like a perfect fit!

@andrew is there anything anyone could do to help out with this? Seems to mostly come down to _you_ running `dat share` to create the canonical version, if I understand correctly.

**Comment by rmg** [comment] 2017-07-10 15:24
I spun up a little droplet on digitalocean (with a dedicated volume for this, since it's too large for the on-device disk) and created, shared, and published 3 separate dats to choose from in case it helps get things rolling:

Uncompressed csv files:
- [rmg/librariesio-csv](https://datproject.org/rmg/librariesio-csv)
- `dat://9cc39cf0aa559c02c34133cf2ad22e89b61b51c94b0cfbc8b0c608573620ef7b`
- **31G**

gzip compressed csv files:
- [rmg/librariesio-csv-gz](https://datproject.org/rmg/librariesio-csv-gz)
- `dat://b39e6298484f71686da3086233aca9e5d68dd7ad7d8c184b36b28c24c9ca03c3`
- **5.6G**

xz compressed csv files:
- [rmg/librariesio-csv-xz](https://datproject.org/rmg/librariesio-csv-xz)
- `dat://2659dde37819d8e6b27c3e1312b407a99a905ad31f228659e1a69afe3ac731d0`
- **3.5G**

@joehand I couldn't find any sort of compression built in to dat. Is there a preferred/recommended way of dealing with large dats? I imagine most CSVs compress pretty well given the nature of the format.

@andrew if you want to `dat clone` any of the above and verify the files then it _might_ save you some legwork/bandwidth/time to just bless one/all of these.

@millette did you stop sharing your dat? I haven't been able to clone it.

**Comment by millette** [comment] 2017-07-10 16:02
Oh, the machine hosting my dat was rebooted, I just restarted sharing it. Sorry.

**Comment by joehand** [comment] 2017-07-10 20:10
@rmg no recommended way yet. We're planning on adding automatic compression for transport, but that isn't implemented yet.

Depending on the use case, it may be useful for them to be uncompressed. But until we add automatic compression that may make it too slow.

**Comment by millette** [comment] 2017-08-27 05:09
I removed the dat I was hosting and updated the OP. Feel free to recreate it of course.

**Comment by andrew** [comment] 2017-10-09 16:35
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.

**Closed by andrew** 2017-10-09 16:35 UTC
Labels: enhancement, open-data, roadmap
