### ISSUE TITLE
API endpoint to retrieve lists of projects

### ISSUE THREAD

**Issue by AlexandreDecan** [librariesio/libraries.io#1289] opened 2017-03-16 13:09 UTC
Hello, 

Here's a tiny suggestion to provide an API endpoint that can be used to retrieve a list of all monitored projects for a given platform. The list should probably be paginated using the already available ``page`` and ``per_page`` parameters. It could be interesting to be able to sort the results like what it is already possible to do with the web view (ie. by name, by latest release date, by rank, by the number of (reverse) dependencies, etc.). 

Incidentally, I suggest to add another API endpoint which can be used to retrieve the list of platforms that are currently supported by libraries.io. This is probably less interesting, but does not represent a huge amount of work (I believe, because I'm clearly not enough fluent in Ruby to do that!).

**Comment by andrew** [comment] 2017-03-16 13:22
@AlexandreDecan you can use the search endpoint to get a list of all projects for a given platform, just don't pass any `query` parameter and it will be unfiltered.

As for list of platforms, yeah that sounds like a good idea!

**Comment by AlexandreDecan** [comment] 2017-03-16 13:32
Oh, I didn't think about making use of the search endpoint for that :) Thank you!
Btw, it could be interesting to add some words about this in the API documentation. 

This leads to some other questions/remarks: 
 - Is there any way to filter out search results by platform? 
 - Also, it seems that search results are paginated by default, and one can use ``page`` and ``per_page`` to navigate through the results. But is there any easy way to know the number of pages that are available? 
 - It also seems that results are sorted according to their rank. I don't know if there's a way to change this? In particular, it could be interesting to allow one to sort the results according to the creation date (in reverse order). This way, one can navigate through the paginated list of projects and any project added during the navigation will only shift the results by one, leading to a duplication but not to a missing value (I'm not sure I'm understandable about this ^^).

**Comment by andrew** [comment] 2017-03-16 14:06
@AlexandreDecan sorry about the lack of documentation, we've got a rather sparse ticket open to improve it: https://github.com/librariesio/libraries.io/issues/198

The search api takes the same parameters as the web search interface, so for example:

    https://libraries.io/search?keywords=react&languages=JavaScript&licenses=MIT&platforms=NPM&sort=stars

translates to:

    https://libraries.io/api/search?keywords=react&languages=JavaScript&licenses=MIT&platforms=NPM&sort=stars

Pagination info is available via Link, Per-Page and Total headers in the response:

![screen shot 2017-03-16 at 2 05 51 pm](https://cloud.githubusercontent.com/assets/1060/23999928/bd996cde-0a51-11e7-9f67-292750579959.png)

**Comment by andrew** [comment] 2017-03-16 14:07
Just noticed a bug in the link headers that don't include all the passed params 🙈

**Comment by AlexandreDecan** [comment] 2017-03-16 15:24
Great, thank you!

(I noticed that this API endpoint does not require an API key. Is this a bug?)

**Comment by andrew** [comment] 2017-03-16 16:26
@AlexandreDecan not a bug but another undocumented feature, if you don't pass an API key you get a much lower rate limit based on your IP address, good for small examples and browser based things

**Comment by AlexandreDecan** [comment] 2017-03-16 16:41
Ok, thanks, nice to know ;-)

**Comment by andrew** [comment] 2017-03-28 13:05
@AlexandreDecan just deployed an endpoint to list all supported platforms: https://libraries.io/api/platforms

**Comment by AlexandreDecan** [comment] 2017-03-28 13:54
Thank you!

**Comment by andrew** [comment] 2017-06-05 12:31
@AlexandreDecan I think everything here has been solved, going to close this issue now

**Closed by andrew** 2017-06-05 12:31 UTC
Labels: API, enhancement
