### ISSUE TITLE
Tilde is not processed correctly

### ISSUE THREAD

**Issue by Jean85** [librariesio/libraries.io#913] opened 2016-11-22 09:38 UTC
I've found this wrong warning sign on my library:

https://libraries.io/packagist/facile-it%2Fparaunit-testcase

![schermata del 2016-11-22 10-35-58](https://cloud.githubusercontent.com/assets/6729988/20518525/c52336c6-b09f-11e6-8bd1-9b89c7a9b758.png)

The requirement is `~1.3`, so latest stable `1.6.x` is compatible, but it's shown as outdated.

**Comment by andrew** [comment] 2016-11-22 15:11
Also affects rubygems (https://github.com/librariesio/libraries.io/issues/337), will need to be fixed in https://github.com/librariesio/semantic_range

**Comment by andrew** [comment] 2016-12-12 15:58
Closing this as a dupe of #337

**Closed by andrew** 2016-12-12 15:58 UTC
Labels: bug

**Comment by andrew** [comment] 2016-12-20 16:07
@Jean85 just deploying a fix for this now
